- src/docs/README.md
#18 
開発手順について書きました．
とりあえずやることは書いた．
説明不十分と思われます．加筆前提です．
> 開発ドキュメント: 手順

- .eslintignore
- .eslintrc.json
- .github/workflows/lint.yml
- .vscode/extensions.json
- .vscode/settings.json
- package.json
- src/.vuepress/config.ts
- yarn.lock
#30 
linter+formatterを追加しました(ESLint+Prettier)．
```bash
yarn lint
yarn fix
```
コード整形を義務付けるため
> *.js, *.ts, *.vue向けのlinter+formatterを追加

- .github/workflows/deploy.yml
- src/.vitepress/config.ts
- src/public/CNAME
デプロイactionsを追加しました.
`main`にpushするとデプロイされるはずです.
(Related to #3)
本番デプロイのため
> デプロイactionsの追加

- package.json
- src/docs/index.md
- yarn.lock
Update node modules with [raineorshine/npm-check-updates](https://github.com/raineorshine/npm-check-updates).
> Update node modules

- scripts/newLang.js
> add error message

- src/.vitepress/theme/components/HLDocAfter.vue
- src/about/index.md
- src/booklet/index.md
> solve #159

- src/.vitepress/theme/components/HLConverter.vue
- src/tools/index.md
> solve #195

- package.json
- scripts/font.ts
- scripts/newLang.ts
- scripts/newOlym.ts
- src/.vitepress/utils/getPosts.ts
- src/.vitepress/utils/newPost.ts
- tsconfig.json
- yarn.lock
> solve #259

- src/.vitepress/theme/components/HLConverter.vue
- src/.vitepress/theme/components/HLDocAfter.vue
- src/.vitepress/theme/shims-vue.d.ts
- tsconfig.json
> solve #261

- package.json
- src/.vitepress/utils/font.ts
- src/.vitepress/utils/newLang.ts
- src/.vitepress/utils/newOlym.ts
> solve #263

- .github/workflows/build-test.yml
- .github/workflows/deploy.yml
- .github/workflows/lint.yml
> デプロイとビルドテストのactionsを分ける

- .github/workflows/deploy.yml
> environment消した

- .github/workflows/deploy-prev.yml
- .github/workflows/deploy-prod.yml
> solve #300

- src/.vitepress/theme/components/HLTags.vue
> タグページが切り替わらないのを修正

- src/.vitepress/theme/components/HLPages.vue
- src/.vitepress/theme/components/HLTags.vue
> 切り替わらないのを修正

- src/.vitepress/config.ts
> set cleanUrls

- src/docs/deu.md
- src/docs/fra.md
- src/docs/grammar-terms.md
- src/docs/grc.md
- src/docs/kor.md
- src/docs/lat.md
- src/docs/rus.md
- src/docs/spa.md
- src/docs/udhr.md
- src/docs/zho.md
- src/public/admin/config.yml
> slugを記事IDに改名

- src/public/admin/config.yml
> オリンピック関連記事のフォームを追加

- src/public/admin/config.yml
> fix media_folder

- src/.vitepress/theme/components/HLNetlifyCMS.vue
- src/public/admin/config.yml
> Netlify CMSの設定調整

- src/.vitepress/theme/components/HLPages.vue
> 記事一覧のリンク修正

- package.json
- src/.vitepress/scripts/getPosts.ts
- src/.vitepress/scripts/git.ts
- src/.vitepress/theme/components/HLPageInfo.vue
- src/.vitepress/theme/components/HLPages.vue
- src/.vitepress/theme/components/HLTags.vue
- src/.vitepress/theme/components/layout/HLDocBefore.vue
- src/.vitepress/theme/index.ts
- src/docs/conv-ain.md
- src/docs/conv-ara.md
- src/docs/conv-chu.md
- src/docs/conv-cop.md
- src/docs/conv-glag.md
- src/docs/conv-grc.md
- src/docs/conv-ipa.md
- src/docs/conv-lat.md
- src/docs/conv-nag.md
- src/docs/conv-rus.md
- src/docs/conv-srp.md
- src/docs/conv-ukr.md
- src/docs/conv-yid.md
- src/docs/conv.md
- yarn.lock
> タグ一覧の機能等の更新

- src/.vitepress/theme/components/HLPages.vue
> ページ番号リンクが反応しないのを修正

- src/.vitepress/theme/components/HLNetlifyCMS.vue
- src/public/netlifycms.yml
> downgrade netlify-cms to 2.9.7

- src/public/netlifycms.yml
> 固定ページのフォームを暫定的に追加

- src/.vitepress/theme/components/HLAuthor.vue
> 著者表示が空配列でも表示されるバグを修正

- src/.vitepress/categories/docs.json
- src/public/netlifycms.yml
> 第二外国語カテゴリを追加

- src/.vitepress/theme/components/layout/HLDocBefore.vue
- src/.vitepress/theme/scss/index.scss
- src/.vitepress/theme/scss/theme-default/VPDocFooter.scss
> レイアウト崩れを修正

- src/.vitepress/theme/components/HLDecapCMS.vue
- src/.vitepress/theme/index.ts
- src/edit.md
- src/public/decapcms.yml
close #433
#318 で導入された Netlify CMS を更新し, Decap CMS v3.0.12 に
#433 が解決したようなので
問題があれば戻します
> Decap CMS (旧 Netlify CMS) の更新

- .vscode/settings.json
- src/.vitepress/config.ts
navにInstagramへのリンクを追加
Instagramの投稿も増えてきたため
> Instagram を追加

- src/.vitepress/config.ts
> オリンピックへのリンクをnoteに

- src/public/_redirects
> fix: リダイレクト漏れ

- src/public/_redirects
> fix: /docs/chu のリダイレクトを修正
